//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.15 at 05:57:19 PM IST 
//


package com.chbase.thing.oxm.jaxb.hba1x;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hba1c.thing.wc.microsoft.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hba1c.thing.wc.microsoft.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HbA1C }
     * 
     */
    public HbA1C createHbA1C() {
        return new HbA1C();
    }

    /**
     * Create an instance of {@link HbA1CValue }
     * 
     */
    public HbA1CValue createHbA1CValue() {
        return new HbA1CValue();
    }

}
