//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.15 at 05:57:19 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com.microsoft.wc.thing.HbA1C")
package com.chbase.thing.oxm.jaxb.hba1x;
