//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 03:45:28 PM IST 
//


package com.chbase.thing.oxm.jaxb.sdtc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.chbase.thing.oxm.jaxb.ccd.POCDMT000040AssignedEntity;


/**
 * <p>Java class for SdtcAssignedEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SdtcAssignedEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}POCD_MT000040.AssignedEntity">
 *       &lt;sequence>
 *         &lt;element name="patient" type="{urn:hl7-org:sdtc}SdtcPatient" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SdtcAssignedEntity", propOrder = {
    "patient"
})
public class SdtcAssignedEntity
    extends POCDMT000040AssignedEntity
{

    protected SdtcPatient patient;

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link SdtcPatient }
     *     
     */
    public SdtcPatient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link SdtcPatient }
     *     
     */
    public void setPatient(SdtcPatient value) {
        this.patient = value;
    }

}
