//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.15 at 05:49:36 PM IST 
//


package com.chbase.thing.oxm.jaxb.passwordprotectedpackage;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _package._protected.password.thing.wc.microsoft.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _package._protected.password.thing.wc.microsoft.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PasswordProtectedPackage }
     * 
     */
    public PasswordProtectedPackage createPasswordProtectedPackage() {
        return new PasswordProtectedPackage();
    }

    /**
     * Create an instance of {@link PackageEncryptionType }
     * 
     */
    public PackageEncryptionType createPackageEncryptionType() {
        return new PackageEncryptionType();
    }

    /**
     * Create an instance of {@link PbeParametersType }
     * 
     */
    public PbeParametersType createPbeParametersType() {
        return new PbeParametersType();
    }

}
