//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:17:58 PM PST 
//

package com.microsoft.hsg.methods.jaxb.beginputblob.request;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.microsoft.hsg.methods.jaxb.JaxbRequest;
import com.microsoft.hsg.methods.jaxb.getthings3.request.ThingRequestGroup2;
import com.microsoft.hsg.thing.oxm.jaxb.types.BlobHashAlgorithmParameters;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="blob-ref-url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="blob-chunk-size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="max-blob-size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="blob-hash-algorithm" type="{urn:com.microsoft.wc.types}stringz255"/>
 *         &lt;element name="blob-hash-parameters" type="{urn:com.microsoft.wc.types}BlobHashAlgorithmParameters"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@JaxbRequest(methodName = "BeginPutBlob", methodVersion = "1", responseNS = "urn:com.microsoft.wc.methods.response.BeginPutBlob")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "" })
@XmlRootElement(name = "info")
public class BeginPutBlobRequest {

	@XmlElement(name = "blob-ref-url", required = true)
	protected String blobRefUrl;

	public String getBlobRefUrl() {
		return blobRefUrl;
	}
}
